using System.Xml.Linq;

namespace PensionCalculator_API.Enums
{
    using System;
    using System.Collections.Generic;

    public enum Country
    {
        AFGHANISTAN = 1,
        ALBANIA,
        ALGERIA,
        ANDORRA,
        ANGOLA,
        ANTIGUA_AND_BARBUDA,
        ARGENTINA,
        ARMENIA,
        AUSTRALIA,
        AUSTRIA,
        AZERBAIJAN,
        BAHAMAS,
        BAHRAIN,
        BANGLADESH,
        BARBADOS,
        BELARUS,
        BELGIUM,
        BELIZE,
        BENIN,
        BHUTAN,
        BOLIVIA,
        BOSNIA_AND_HERZEGOVINA,
        BOTSWANA,
        BRAZIL,
        BRUNEI,
        BULGARIA,
        BURKINA_FASO,
        BURUNDI,
        CABO_VERDE,
        CAMBODIA,
        CAMEROON,
        CANADA,
        CENTRAL_AFRICAN_REPUBLIC,
        CHAD,
        CHILE,
        CHINA,
        COLOMBIA,
        COMOROS,
        CONGO,
        COSTA_RICA,
        CROATIA,
        CUBA,
        CYPRUS,
        CZECH_REPUBLIC,
        DENMARK,
        DJIBOUTI,
        DOMINICA,
        DOMINICAN_REPUBLIC,
        ECUADOR,
        EGYPT,
        EL_SALVADOR,
        ETHIOPIA,
        FINLAND,
        FRANCE,
        GABON,
        GAMBIA,
        GEORGIA,
        GERMANY,
        GHANA,
        GREECE,
        GRENADA,
        GUATEMALA,
        GUINEA,
        GUINEA_BISSAU,
        GUYANA,
        HAITI,
        HONDURAS,
        HUNGARY,
        ICELAND,
        INDIA,
        INDONESIA,
        IRAN,
        IRAQ,
        IRELAND,
        ISRAEL,
        ITALY,
        IVORY_COAST,
        JAMAICA,
        JAPAN,
        JORDAN,
        KAZAKHSTAN,
        KENYA,
        KIRIBATI,
        KOSOVO,
        KUWAIT,
        KYRGYZSTAN,
        LAOS,
        LATVIA,
        LEBANON,
        LESOTHO,
        LIBERIA,
        LIBYA,
        LIECHTENSTEIN,
        LITHUANIA,
        LUXEMBOURG,
        MADAGASCAR,
        MALAWI,
        MALAYSIA,
        MALDIVES,
        MALI,
        MALTA,
        MARSHALL_ISLANDS,
        MAURITANIA,
        MAURITIUS,
        MEXICO,
        MICRONESIA,
        MOLDOVA,
        MONACO,
        MONGOLIA,
        MONTENEGRO,
        MOROCCO,
        MOZAMBIQUE,
        MYANMAR,
        NAMIBIA,
        NAURU,
        NEPAL,
        NETHERLANDS,
        NEW_ZEALAND,
        NICARAGUA,
        NIGER,
        NIGERIA,
        NORTH_KOREA,
        NORTH_MACEDONIA,
        NORWAY,
        OMAN,
        PAKISTAN,
        PALAU,
        PANAMA,
        PAPUA_NEW_GUINEA,
        PARAGUAY,
        PERU,
        PHILIPPINES,
        POLAND,
        PORTUGAL,
        QATAR,
        ROMANIA,
        RUSSIA,
        RWANDA,
        SAINT_KITTS_AND_NEVIS,
        SAINT_LUCIA,
        SAINT_VINCENT_AND_THE_GRENADINES,
        SAMOA,
        SAN_MARINO,
        SAO_TOME_AND_PRINCIPE,
        SAUDI_ARABIA,
        SENEGAL,
        SERBIA,
        SEYCHELLES,
        SIERRA_LEONE,
        SINGAPORE,
        SLOVAKIA,
        SLOVENIA,
        SOLOMON_ISLANDS,
        SOMALIA,
        SOUTH_AFRICA,
        SOUTH_KOREA,
        SOUTH_SUDAN,
        SPAIN,
        SRI_LANKA,
        SUDAN,
        SURINAME,
        SWEDEN,
        SWITZERLAND,
        SYRIA,
        TAJIKISTAN,
        TANZANIA,
        THAILAND,
        TIMOR_LESTE,
        TOGO,
        TONGA,
        TRINIDAD_AND_TOBAGO,
        TUNISIA,
        TURKEY,
        TURKMENISTAN,
        TUVALU,
        UGANDA,
        UKRAINE,
        UNITED_ARAB_EMIRATES,
        UNITED_KINGDOM,
        UNITED_STATES,
        URUGUAY,
        UZBEKISTAN,
        VANUATU,
        VATICAN_CITY,
        VENEZUELA,
        VIETNAM,
        YEMEN,
        ZAMBIA,
        ZIMBABWE
    }

    public class CountryInfo
    {
        public string Code { get; }
        public string Name { get; }

        public CountryInfo(string code, string name)
        {
            Code = code;
            Name = name;
        }
    }

    public static class CountryExtensions
    {
        private static readonly Dictionary<Country, CountryInfo> CountryDetails = new Dictionary<Country, CountryInfo>
        {
            { Country.AFGHANISTAN, new CountryInfo("AFG", "Afghanistan") },
            { Country.ALBANIA, new CountryInfo("ALB", "Albania") },
            { Country.ALGERIA, new CountryInfo("DZA", "Algeria") },
            { Country.ANDORRA, new CountryInfo("AND", "Andorra") },
            { Country.ANGOLA, new CountryInfo("AGO", "Angola") },
            { Country.ANTIGUA_AND_BARBUDA, new CountryInfo("ATG", "Antigua and Barbuda") },
            { Country.ARGENTINA, new CountryInfo("ARG", "Argentina") },
            { Country.ARMENIA, new CountryInfo("ARM", "Armenia") },
            { Country.AUSTRALIA, new CountryInfo("AUS", "Australia") },
            { Country.AUSTRIA, new CountryInfo("AUT", "Austria") },
            { Country.AZERBAIJAN, new CountryInfo("AZE", "Azerbaijan") },
            { Country.BAHAMAS, new CountryInfo("BHS", "Bahamas") },
            { Country.BAHRAIN, new CountryInfo("BHR", "Bahrain") },
            { Country.BANGLADESH, new CountryInfo("BGD", "Bangladesh") },
            { Country.BARBADOS, new CountryInfo("BRB", "Barbados") },
            { Country.BELARUS, new CountryInfo("BLR", "Belarus") },
            { Country.BELGIUM, new CountryInfo("BEL", "Belgium") },
            { Country.BELIZE, new CountryInfo("BLZ", "Belize") },
            { Country.BENIN, new CountryInfo("BEN", "Benin") },
            { Country.BHUTAN, new CountryInfo("BTN", "Bhutan") },
            { Country.BOLIVIA, new CountryInfo("BOL", "Bolivia") },
            { Country.BOSNIA_AND_HERZEGOVINA, new CountryInfo("BIH", "Bosnia and Herzegovina") },
            { Country.BOTSWANA, new CountryInfo("BWA", "Botswana") },
            { Country.BRAZIL, new CountryInfo("BRA", "Brazil") },
            { Country.BRUNEI, new CountryInfo("BRN", "Brunei") },
            { Country.BULGARIA, new CountryInfo("BGR", "Bulgaria") },
            { Country.BURKINA_FASO, new CountryInfo("BFA", "Burkina Faso") },
            { Country.BURUNDI, new CountryInfo("BDI", "Burundi") },
            { Country.CABO_VERDE, new CountryInfo("CPV", "Cabo Verde") },
            { Country.CAMBODIA, new CountryInfo("KHM", "Cambodia") },
            { Country.CAMEROON, new CountryInfo("CMR", "Cameroon") },
            { Country.CANADA, new CountryInfo("CAN", "Canada") },
            { Country.CENTRAL_AFRICAN_REPUBLIC, new CountryInfo("CAF", "Central African Republic") },
            { Country.CHAD, new CountryInfo("TCD", "Chad") },
            { Country.CHILE, new CountryInfo("CHL", "Chile") },
            { Country.CHINA, new CountryInfo("CHN", "China") },
            { Country.COLOMBIA, new CountryInfo("COL", "Colombia") },
            { Country.COMOROS, new CountryInfo("COM", "Comoros") },
            { Country.CONGO, new CountryInfo("COG", "Congo") },
            { Country.COSTA_RICA, new CountryInfo("CRI", "Costa Rica") },
            { Country.CROATIA, new CountryInfo("HRV", "Croatia") },
            { Country.CUBA, new CountryInfo("CUB", "Cuba") },
            { Country.CYPRUS, new CountryInfo("CYP", "Cyprus") },
            { Country.CZECH_REPUBLIC, new CountryInfo("CZE", "Czech Republic") },
            { Country.DENMARK, new CountryInfo("DNK", "Denmark") },
            { Country.DJIBOUTI, new CountryInfo("DJI", "Djibouti") },
            { Country.DOMINICA, new CountryInfo("DMA", "Dominica") },
            { Country.DOMINICAN_REPUBLIC, new CountryInfo("DOM", "Dominican Republic") },
            { Country.ECUADOR, new CountryInfo("ECU", "Ecuador") },
            { Country.EGYPT, new CountryInfo("EGY", "Egypt") },
            { Country.EL_SALVADOR, new CountryInfo("SLV", "El Salvador") },
            { Country.ETHIOPIA, new CountryInfo("ETH", "Ethiopia") },
            { Country.FINLAND, new CountryInfo("FIN", "Finland") },
            { Country.FRANCE, new CountryInfo("FRA", "France") },
            { Country.GABON, new CountryInfo("GAB", "Gabon") },
            { Country.GAMBIA, new CountryInfo("GMB", "Gambia") },
            { Country.GEORGIA, new CountryInfo("GEO", "Georgia") },
            { Country.GERMANY, new CountryInfo("DEU", "Germany") },
            { Country.GHANA, new CountryInfo("GHA", "Ghana") },
            { Country.GREECE, new CountryInfo("GRC", "Greece") },
            { Country.GRENADA, new CountryInfo("GRD", "Grenada") },
            { Country.GUATEMALA, new CountryInfo("GTM", "Guatemala") },
            { Country.GUINEA, new CountryInfo("GIN", "Guinea") },
            { Country.GUINEA_BISSAU, new CountryInfo("GNB", "Guinea-Bissau") },
            { Country.GUYANA, new CountryInfo("GUY", "Guyana") },
            { Country.HAITI, new CountryInfo("HTI", "Haiti") },
            { Country.HONDURAS, new CountryInfo("HND", "Honduras") },
            { Country.HUNGARY, new CountryInfo("HUN", "Hungary") },
            { Country.ICELAND, new CountryInfo("ISL", "Iceland") },
            { Country.INDIA, new CountryInfo("IND", "India") },
            { Country.INDONESIA, new CountryInfo("IDN", "Indonesia") },
            { Country.IRAN, new CountryInfo("IRN", "Iran") },
            { Country.IRAQ, new CountryInfo("IRQ", "Iraq") },
            { Country.IRELAND, new CountryInfo("IRL", "Ireland") },
            { Country.ISRAEL, new CountryInfo("ISR", "Israel") },
            { Country.ITALY, new CountryInfo("ITA", "Italy") },
            { Country.IVORY_COAST, new CountryInfo("CIV", "Ivory Coast") },
            { Country.JAMAICA, new CountryInfo("JAM", "Jamaica") },
            { Country.JAPAN, new CountryInfo("JPN", "Japan") },
            { Country.JORDAN, new CountryInfo("JOR", "Jordan") },
            { Country.KAZAKHSTAN, new CountryInfo("KAZ", "Kazakhstan") },
            { Country.KENYA, new CountryInfo("KEN", "Kenya") },
            { Country.KIRIBATI, new CountryInfo("KIR", "Kiribati") },
            { Country.KOSOVO, new CountryInfo("XKX", "Kosovo") },
            { Country.KUWAIT, new CountryInfo("KWT", "Kuwait") },
            { Country.KYRGYZSTAN, new CountryInfo("KGZ", "Kyrgyzstan") },
            { Country.LAOS, new CountryInfo("LAO", "Laos") },
            { Country.LATVIA, new CountryInfo("LVA", "Latvia") },
            { Country.LEBANON, new CountryInfo("LBN", "Lebanon") },
            { Country.LESOTHO, new CountryInfo("LSO", "Lesotho") },
            { Country.LIBERIA, new CountryInfo("LBR", "Liberia") },
            { Country.LIBYA, new CountryInfo("LBY", "Libya") },
            { Country.LIECHTENSTEIN, new CountryInfo("LIE", "Liechtenstein") },
            { Country.LITHUANIA, new CountryInfo("LTU", "Lithuania") },
            { Country.LUXEMBOURG, new CountryInfo("LUX", "Luxembourg") },
            { Country.MADAGASCAR, new CountryInfo("MDG", "Madagascar") },
            { Country.MALAWI, new CountryInfo("MWI", "Malawi") },
            { Country.MALAYSIA, new CountryInfo("MYS", "Malaysia") },
            { Country.MALDIVES, new CountryInfo("MDV", "Maldives") },
            { Country.MALI, new CountryInfo("MLI", "Mali") },
            { Country.MALTA, new CountryInfo("MLT", "Malta") },
            { Country.MARSHALL_ISLANDS, new CountryInfo("MHL", "Marshall Islands") },
            { Country.MAURITANIA, new CountryInfo("MRT", "Mauritania") },
            { Country.MAURITIUS, new CountryInfo("MUS", "Mauritius") },
            { Country.MEXICO, new CountryInfo("MEX", "Mexico") },
            { Country.MICRONESIA, new CountryInfo("FSM", "Micronesia") },
            { Country.MOLDOVA, new CountryInfo("MDA", "Moldova") },
            { Country.MONACO, new CountryInfo("MCO", "Monaco") },
            { Country.MONGOLIA, new CountryInfo("MNG", "Mongolia") },
            { Country.MONTENEGRO, new CountryInfo("MNE", "Montenegro") },
            { Country.MOROCCO, new CountryInfo("MAR", "Morocco") },
            { Country.MOZAMBIQUE, new CountryInfo("MOZ", "Mozambique") },
            { Country.MYANMAR, new CountryInfo("MMR", "Myanmar") },
            { Country.NAMIBIA, new CountryInfo("NAM", "Namibia") },
            { Country.NAURU, new CountryInfo("NRU", "Nauru") },
            { Country.NEPAL, new CountryInfo("NPL", "Nepal") },
            { Country.NETHERLANDS, new CountryInfo("NLD", "Netherlands") },
            { Country.NEW_ZEALAND, new CountryInfo("NZL", "New Zealand") },
            { Country.NICARAGUA, new CountryInfo("NIC", "Nicaragua") },
            { Country.NIGER, new CountryInfo("NER", "Niger") },
            { Country.NIGERIA, new CountryInfo("NGA", "Nigeria") },
            { Country.NORTH_KOREA, new CountryInfo("PRK", "North Korea") },
            { Country.NORTH_MACEDONIA, new CountryInfo("MKD", "North Macedonia") },
            { Country.NORWAY, new CountryInfo("NOR", "Norway") },
            { Country.OMAN, new CountryInfo("OMN", "Oman") },
            { Country.PAKISTAN, new CountryInfo("PAK", "Pakistan") },
            { Country.PALAU, new CountryInfo("PLW", "Palau") },
            { Country.PANAMA, new CountryInfo("PAN", "Panama") },
            { Country.PAPUA_NEW_GUINEA, new CountryInfo("PNG", "Papua New Guinea") },
            { Country.PARAGUAY, new CountryInfo("PRY", "Paraguay") },
            { Country.PERU, new CountryInfo("PER", "Peru") },
            { Country.PHILIPPINES, new CountryInfo("PHL", "Philippines") },
            { Country.POLAND, new CountryInfo("POL", "Poland") },
            { Country.PORTUGAL, new CountryInfo("PRT", "Portugal") },
            { Country.QATAR, new CountryInfo("QAT", "Qatar") },
            { Country.ROMANIA, new CountryInfo("ROU", "Romania") },
            { Country.RUSSIA, new CountryInfo("RUS", "Russia") },
            { Country.RWANDA, new CountryInfo("RWA", "Rwanda") },
            { Country.SAINT_KITTS_AND_NEVIS, new CountryInfo("KNA", "Saint Kitts and Nevis") },
            { Country.SAINT_LUCIA, new CountryInfo("LCA", "Saint Lucia") },
            { Country.SAINT_VINCENT_AND_THE_GRENADINES, new CountryInfo("VCT", "Saint Vincent and the Grenadines") },
            { Country.SAMOA, new CountryInfo("WSM", "Samoa") },
            { Country.SAN_MARINO, new CountryInfo("SMR", "San Marino") },
            { Country.SAO_TOME_AND_PRINCIPE, new CountryInfo("STP", "Sao Tome and Principe") },
            { Country.SAUDI_ARABIA, new CountryInfo("SAU", "Saudi Arabia") },
            { Country.SENEGAL, new CountryInfo("SEN", "Senegal") },
            { Country.SERBIA, new CountryInfo("SRB", "Serbia") },
            { Country.SEYCHELLES, new CountryInfo("SYC", "Seychelles") },
            { Country.SIERRA_LEONE, new CountryInfo("SLE", "Sierra Leone") },
            { Country.SINGAPORE, new CountryInfo("SGP", "Singapore") },
            { Country.SLOVAKIA, new CountryInfo("SVK", "Slovakia") },
            { Country.SLOVENIA, new CountryInfo("SVN", "Slovenia") },
            { Country.SOLOMON_ISLANDS, new CountryInfo("SLB", "Solomon Islands") },
            { Country.SOMALIA, new CountryInfo("SOM", "Somalia") },
            { Country.SOUTH_AFRICA, new CountryInfo("ZAF", "South Africa") },
            { Country.SOUTH_KOREA, new CountryInfo("KOR", "South Korea") },
            { Country.SOUTH_SUDAN, new CountryInfo("SSD", "South Sudan") },
            { Country.SPAIN, new CountryInfo("ESP", "Spain") },
            { Country.SRI_LANKA, new CountryInfo("LKA", "Sri Lanka") },
            { Country.SUDAN, new CountryInfo("SDN", "Sudan") },
            { Country.SURINAME, new CountryInfo("SUR", "Suriname") },
            { Country.SWEDEN, new CountryInfo("SWE", "Sweden") },
            { Country.SWITZERLAND, new CountryInfo("CHE", "Switzerland") },
            { Country.SYRIA, new CountryInfo("SYR", "Syria") },
            { Country.TAJIKISTAN, new CountryInfo("TJK", "Tajikistan") },
            { Country.TANZANIA, new CountryInfo("TZA", "Tanzania") },
            { Country.THAILAND, new CountryInfo("THA", "Thailand") },
            { Country.TIMOR_LESTE, new CountryInfo("TLS", "Timor-Leste") },
            { Country.TOGO, new CountryInfo("TGO", "Togo") },
            { Country.TONGA, new CountryInfo("TON", "Tonga") },
            { Country.TRINIDAD_AND_TOBAGO, new CountryInfo("TTO", "Trinidad and Tobago") },
            { Country.TUNISIA, new CountryInfo("TUN", "Tunisia") },
            { Country.TURKEY, new CountryInfo("TUR", "Turkey") },
            { Country.TURKMENISTAN, new CountryInfo("TKM", "Turkmenistan") },
            { Country.TUVALU, new CountryInfo("TUV", "Tuvalu") },
            { Country.UGANDA, new CountryInfo("UGA", "Uganda") },
            { Country.UKRAINE, new CountryInfo("UKR", "Ukraine") },
            { Country.UNITED_ARAB_EMIRATES, new CountryInfo("ARE", "United Arab Emirates") },
            { Country.UNITED_KINGDOM, new CountryInfo("GBR", "United Kingdom") },
            { Country.UNITED_STATES, new CountryInfo("USA", "United States") },
            { Country.URUGUAY, new CountryInfo("URY", "Uruguay") },
            { Country.UZBEKISTAN, new CountryInfo("UZB", "Uzbekistan") },
            { Country.VANUATU, new CountryInfo("VUT", "Vanuatu") },
            { Country.VATICAN_CITY, new CountryInfo("VAT", "Vatican City") },
            { Country.VENEZUELA, new CountryInfo("VEN", "Venezuela") },
            { Country.VIETNAM, new CountryInfo("VNM", "Vietnam") },
            { Country.YEMEN, new CountryInfo("YEM", "Yemen") },
            { Country.ZAMBIA, new CountryInfo("ZMB", "Zambia") },
            { Country.ZIMBABWE, new CountryInfo("ZWE", "Zimbabwe") }
        };


        public static CountryInfo GetCountryInfo(this Country country)
        {
            return CountryDetails.ContainsKey(country) ? CountryDetails[country] : null;
        }

        public static Country? GetCountryByCode(string code)
        {
            foreach (var entry in CountryDetails)
            {
                if (entry.Value.Code.Equals(code, StringComparison.OrdinalIgnoreCase))
                {
                    return entry.Key;
                }
            }
            return null;
        }
    }
}
